### PR TITLE
Add options DELIMITER/SKIP_ROWS/HEADER in dataframe

### PR DESCRIPTION
**Pull request by prutskov**

### CODE REVIEW

**Comment by alexbaden** [comment]
Looks good, other than the `clang-tidy` failure:
```
[ 42%] Building CXX object DataMgr/CMakeFiles/DataMgr.dir/BufferMgr/Buffer.cpp.o
/home/jenkins-slave/workspace/core-clang-tidy-pr/DataMgr/ForeignStorage/ArrowCsvForeignStorage.cpp: In member function ‘virtual void ArrowCsvForeignStorage::registerTable(Catalog_Namespace::Catalog*, std::pair<int, int>, const string&, const TableDescriptor&, const std::__cxx11::list<ColumnDescriptor>&, Data_Namespace::AbstractBufferMgr*, int32_t)’:
/home/jenkins-slave/workspace/core-clang-tidy-pr/DataMgr/ForeignStorage/ArrowCsvForeignStorage.cpp:229:8: error: ‘struct arrow::csv::ReadOptions’ has no member named ‘skip_rows’
   ropt.skip_rows = skip_rows;
        ^~~~~~~~~
/home/jenkins-slave/workspace/core-clang-tidy-pr/DataMgr/ForeignStorage/ArrowCsvForeignStorage.cpp:240:10: error: ‘struct arrow::csv::ReadOptions’ has no member named ‘column_names’
     ropt.column_names.push_back(c.columnName);
          ^~~~~~~~~~~~
make[2]: *** [DataMgr/CMakeFiles/DataMgr.dir/ForeignStorage/ArrowCsvForeignStorage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by prutskov** [comment]
@alexbaden This changes will work with arrow 15.1. This PR will be merged after updating arrow in OmniSci (I forgot to notify, sorry).

**Comment by prutskov** [comment]
@alexbaden Please, can someone review this PR?

**Comment by prutskov** [comment]
This was merged already in other PR. I close this PR.
